/* global React */
/* Editorial fixture data — taken from feel of ozanefeoglu.com sample seeds.
   No real photos: covers fall back to typo-cover or PhotoPlaceholder. */

window.WRITINGS = [
  {
    id: "kasanin-altindaki-sehir",
    kind: "saha_yazisi",
    kindLabel: "Saha yazısı",
    title: "Kasanın altındaki şehir",
    excerpt: "Hatay'da bir kahvenin tezgâhında, kasa makinesinin ses çıkarmadığı saatlerde, bir başka şehir kuruluyordu.",
    location: "Hatay",
    date: "2026-04-26",
    dateLong: "26 Nisan 2026",
    dateShort: "26.04.2026",
    monthDay: "26.04",
    readMins: 14,
    hasCover: false,
  },
  {
    id: "drone-not-defteri",
    kind: "roportaj",
    kindLabel: "Röportaj",
    title: "Bir foto‑muhabirin not defteri",
    excerpt: "Drone'la haber yapmanın etiği üzerine bir saatlik kayıt; izin, görsel göstergebilim ve mesafe.",
    location: "İstanbul",
    date: "2026-04-12",
    dateLong: "12 Nisan 2026",
    dateShort: "12.04.2026",
    monthDay: "12.04",
    readMins: 22,
    hasCover: false,
  },
  {
    id: "saf-siyah",
    kind: "deneme",
    kindLabel: "Deneme",
    title: "Saf siyah dijital bir yalandır",
    excerpt: "Mürekkep, kâğıt ve kalibrasyon: gerçek bir karanlığı ekrana getirmenin imkânı üzerine.",
    location: null,
    date: "2026-04-03",
    dateLong: "3 Nisan 2026",
    dateShort: "03.04.2026",
    monthDay: "03.04",
    readMins: 8,
    hasCover: false,
  },
  {
    id: "kabin-saha-defteri",
    kind: "not",
    kindLabel: "Not",
    title: "Kabin · saha defteri 016",
    excerpt: "Adana ekspresinin kabininde bir geceyarısı, yedi muhabirin not defteri.",
    location: "Adana",
    date: "2026-03-21",
    dateLong: "21 Mart 2026",
    dateShort: "21.03.2026",
    monthDay: "21.03",
    readMins: 4,
    hasCover: false,
  },
  {
    id: "olive-branch",
    kind: "saha_yazisi",
    kindLabel: "Saha yazısı",
    title: "Zeytin Dalı'ndan iki kare",
    excerpt: "Sınır hattında çekilmiş iki fotoğraf ve bunların açıkladığı bir saatlik bekleyiş.",
    location: "Hatay",
    date: "2026-03-08",
    dateLong: "8 Mart 2026",
    dateShort: "08.03.2026",
    monthDay: "08.03",
    readMins: 11,
    hasCover: false,
  },
  {
    id: "uludag-program",
    kind: "deneme",
    kindLabel: "Deneme",
    title: "Uludağ'da bir bilgisayar programcısı",
    excerpt: "Liseden lisansa, koddan haberciliğe — gizli omurganın günlüğü.",
    location: "Bursa",
    date: "2026-02-18",
    dateLong: "18 Şubat 2026",
    dateShort: "18.02.2026",
    monthDay: "18.02",
    readMins: 7,
    hasCover: false,
  },
  {
    id: "aa-merkez",
    kind: "roportaj",
    kindLabel: "Röportaj",
    title: "Uluslararası haber merkezinin kapısı",
    excerpt: "AA İstanbul'da bir akşam vardiyası: telegram, telefon, tezgâh ve sayfa.",
    location: "İstanbul",
    date: "2026-01-30",
    dateLong: "30 Ocak 2026",
    dateShort: "30.01.2026",
    monthDay: "30.01",
    readMins: 18,
    hasCover: false,
  },
];

window.PHOTO_FRAMES = [
  { idx: 1, loc: "Hatay" },
  { idx: 2, loc: "İstanbul" },
  { idx: 3, loc: "Adana" },
  { idx: 4, loc: "İzmir" },
  { idx: 5, loc: "Bursa" },
  { idx: 6, loc: "Ankara" },
];

window.WORKAREAS = [
  { label: "Saha", title: "Saha yazıları", lines: ["Hatay · Adana · İstanbul", "Zeytin Dalı, sınır hattı"] },
  { label: "Görsel", title: "Foto‑muhabirlik", lines: ["35mm · medium format", "drone — görsel göstergebilim"] },
  { label: "Araştırma", title: "Yüksek lisans", lines: ["İst. Aydın Üniversitesi", "drone haberciliğinin etiği"] },
  { label: "Yayıncılık", title: "Yayın & arşiv", lines: ["ozanefeoglu.com", "saha pratikleri kitabı"] },
];

window.CREDITS = [
  "Anadolu Ajansı", "BirGün", "1+1 Forum", "Topic", "Aperture",
  "İstanbul Modern", "Magnum Foundation",
];
